INSERT INTO embroidery_stitches (stitch_name, image_url, stitch_description)
VALUES (
    ('satin, stitch', 'https://i.imgur.com/TF01BWC.png', 'Straight stitches made beside one another, typically used to fill in an area or shape with solid color.'),
    ('split stitch', 'https://i.imgur.com/THJvmkO.png', 'Start with a straight stitch. Come up through the stitch you just made, and make another straight stitch. Continue making stitches, splitting the thread as you go along.'),
    ('short and long stitch', 'https://i.imgur.com/acoFgC7.png', 'This stitch is usually used to blend colors together, used commonly in thread painting. A series of short and long stitches are used to combine two or more colors together. This is best done with a gradient of colors, dark to light, or light to dark.'),
    ('chain stitch', 'https://i.imgur.com/PS1RC0q.png', 'Bring the thread through the fabric and then back down the same hole Pull partially through until a loop forms. Bring your needle through in the loop and pull snug. Continue making a chain.'),
    ('french knot', 'https://i.imgur.com/woSc0PU.png''Bring thread through the back of the fabric. Take the thread in non-working hand and twist thread around needle 2-3 times. Bring needle down through the initial spot you came up through and pull tight.'),
    ('bullion knot', 'https://i.imgur.com/egla9p0.png', 'Come up through the back of the fabric and take the needle a few cm down from the first stitch and come back up through the same hole the thread is coming through. Take your thread and twist around the needle 6-7 stitches.
    Place your thumb over the stitches to keep them secure and pull your needle all the way through.Secure the stitches at the bottom of the knot'),
    ('stem stitch', 'https://i.imgur.com/1KmLcxs.jpg', 'Come up through the back of the fabric and take a stitch with your needle, coming up about halfway between the first stitch. Pull through, and repeat.'),
    ('back stitch', 'https://i.imgur.com/RwpX0Q7.png','Start with a straight stitch. Come up where your first stitch ends. Come up a space ahead, then stitch backwards where your previous stitch ended.'),
    ('woven wheel', 'https://i.imgur.com/woXPvgu.jpg', 'Make 6 straight stitches around a circle, forming a “star”. Come up through the right of the center point. Weave your thread under and over the 5 points until circle is completely full.'),
    ('fishbone stitch', 'https://i.imgur.com/ZHWrEG1.jpg', 'Make a straight stitch. Bring thread to the side of the initial stitch. Bring needle down to the opposite side of the straight stitch. Alternate sides all the way down leaf shape.'),
    ('fly stitch', 'https://i.imgur.com/ehjhKki.jpg', 'Make one straight stitch. Come up to the left of the initial stitch. Go down to the right of the initial stitch and grab hold of loop. Bring needle up at the base of the straight stitch and then back down below loop.')
)